model:
    glove:
        path_file: "models/glove.6B.50d.txt"
        registry_name: pretrain_glove_model
        current_version: 1.0.0
    label_encoder:
        path_file: "models/label_encoder.joblib"
        registry_name: emojify_label_encoder
        current_version: 1.0.0
    xgb_model:
        path_file: "models/xgboost_model.joblib"
        registry_name: emojify_xgb_classification
        current_version: 1.0.0

prediction:
    top_k: 15

programming:
    comet_api_key: j3DrC3ChXkR42WfPCUh5EIkye
    comet_project_name: emoji-search-app
    comet_workspace: thaiv7